# Generated by Django 5.1.1 on 2024-09-21 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_memberships'),
    ]

    operations = [
        migrations.DeleteModel(
            name='trainer',
        ),
    ]
