# Generated by Django 5.1.1 on 2024-09-21 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_trainer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='trainer',
            new_name='coaches',
        ),
    ]
