# Generated by Django 5.1.1 on 2024-09-21 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_rename_trainer_coaches'),
    ]

    operations = [
        migrations.DeleteModel(
            name='coaches',
        ),
    ]
