# Generated by Django 5.1.1 on 2024-09-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_delete_coaches'),
    ]

    operations = [
        migrations.CreateModel(
            name='coaches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pic')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('desc', models.CharField(max_length=50)),
            ],
        ),
    ]
