# Generated by Django 5.1.1 on 2024-09-28 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_trainer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='trainer',
        ),
    ]
