# Generated by Django 5.1.1 on 2024-09-28 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_delete_trainer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='classes',
        ),
        migrations.DeleteModel(
            name='coaches',
        ),
        migrations.DeleteModel(
            name='memberships',
        ),
    ]
